### ISSUE TITLE
[ZEON] - recommended additions

### ISSUE THREAD

**Issue by zeon-neon** [NeonGamerBot-QK/saahild.com#10]
# Meta

- [ ] Your repo does not have web commit signing off enabled. **PLEASE ENABLE IT** [here](https://github.com/NeonGamerBot-QK/saahild.com/settings)

- [ ] This repo does not have discussions enabled

- [ ] This repo does not have wiki enabled

- [ ] This repo does not have a code of conduct (feature is in beta!)

- [ ] This repo does not have a code of conduct (feature is in beta!)

- [ ] undefined
# Automation

- [ ] **Mark this to override & close this issue.**

**Comment by NeonGamerBot-QK** [comment]
E
